import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import { UploadedDocumentDetail } from "@/lib/uploads";

const styles = StyleSheet.create({
  page: {
    paddingVertical: 48,
    paddingHorizontal: 56,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#18181b",
  },
  h1: { fontSize: 16, fontFamily: "Helvetica-Bold", marginBottom: 4 },
  subtitle: { fontSize: 9, color: "#71717a", marginBottom: 16 },
  h2: { fontSize: 12, fontFamily: "Helvetica-Bold", marginTop: 16, marginBottom: 6 },
  p: { marginBottom: 6, lineHeight: 1.4 },
  card: { marginBottom: 8, padding: 8, backgroundColor: "#fafafa" },
  cardTitle: { fontFamily: "Helvetica-Bold", marginBottom: 2 },
  label: { fontFamily: "Helvetica-Bold" },
  footnote: { fontSize: 8, color: "#a1a1aa", marginTop: 16 },
});

export default function AnalysisReportPdfDocument({ upload }: { upload: UploadedDocumentDetail }) {
  return (
    <Document title={`${upload.filename} — Analysis Report`}>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.h1}>Document Analysis Report</Text>
        <Text style={styles.subtitle}>{upload.filename}</Text>

        {upload.summary && (
          <View>
            <Text style={styles.h2}>Summary</Text>
            <Text style={styles.p}>{upload.summary}</Text>
          </View>
        )}

        {upload.risks && upload.risks.length > 0 && (
          <View>
            <Text style={styles.h2}>Risk Highlights</Text>
            {upload.risks.map((risk, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.cardTitle}>
                  {risk.title} ({risk.severity})
                </Text>
                <Text>{risk.description}</Text>
              </View>
            ))}
          </View>
        )}

        {upload.clauses && upload.clauses.length > 0 && (
          <View>
            <Text style={styles.h2}>Clause Explanation</Text>
            {upload.clauses.map((clause, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.cardTitle}>{clause.clauseTitle}</Text>
                <Text>{clause.plainEnglish}</Text>
              </View>
            ))}
          </View>
        )}

        {upload.comparison && (
          <View>
            <Text style={styles.h2}>Comparison to {upload.comparison.matchedCatalogName}</Text>
            {upload.comparison.deviations.map((deviation, i) => (
              <View key={i} style={styles.card}>
                <Text style={styles.cardTitle}>{deviation.topic}</Text>
                <Text>
                  <Text style={styles.label}>Standard: </Text>
                  {deviation.standardTerm}
                </Text>
                <Text>
                  <Text style={styles.label}>This document: </Text>
                  {deviation.uploadedDocumentTerm}
                </Text>
                <Text>
                  <Text style={styles.label}>Assessment: </Text>
                  {deviation.assessment}
                </Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footnote}>
          Generated by Prelegal AI. This report is informational only and is not legal advice.
        </Text>
      </Page>
    </Document>
  );
}
